name: Scheduled Data Update

on:
  schedule:
    - cron: "45 7 * * *"

env:
  BOT_USER: lc-bot
  DATA_REPO: datarepo
  SECONDARY_REPO: LLNL/llnl.github.io.git
  SECONDARY_BRANCH: main

jobs:
  runDataUpdate:
    name: Run Data Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: thisrepo
      - name: Checkout secondary repo
        uses: actions/checkout@v4
        with:
          repository: $SECONDARY_REPO
          ref: $SECONDARY_BRANCH
          path: $DATA_REPO
          token: ${{ secrets.BOT_TOKEN }}
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "$DATA_REPO/_visualize/scripts/requirements.txt"
      - name: Install dependencies
        run: pip install -r $DATA_REPO/_visualize/scripts/requirements.txt
      - name: Run update script
        shell: bash
        run: ./thisrepo/.github/scripts/update.sh
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      - name: Save log files
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: logfiles
          path: |
            $DATA_REPO/_visualize/LAST_MASTER_UPDATE.txt
            $DATA_REPO/_visualize/LAST_MASTER_UPDATE.log
